version: '3.8'
services:

  school-portal-db:
    container_name: school-portal-db
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge